#!/bin/sh
# This script copies all ACPI tables into /kernel/firmware/acpi
# You must have configfs enabled for this to work

    for TABLE in `ls /kernel/firmware/acpi/ 2>/dev/null`; do
	dest_dir=$(basename $TABLE .aml)
	mkdir /sys/kernel/config/acpi/table/$dest_dir
	cat /kernel/firmware/acpi/$TABLE > /sys/kernel/config/acpi/table/$dest_dir/aml
    done

